
services:
  vicuna:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - "33670:5000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['7']
              capabilities: [gpu]
