# torch 2.2.0
# cuda 12.3.2
# More information can be found in https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html
FROM nvcr.io/nvidia/pytorch:24.01-py3

LABEL author="Shu Zhao, smz5505@psu.edu"
ENV TZ="America/New_York"

RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y tzdata \
  && apt install -y git \
  && apt-get autoremove -y \
  && apt-get clean -y \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /root
RUN git clone https://github.com/haotian-liu/LLaVA.git
WORKDIR /root/LLaVA
RUN pip install --upgrade pip flask && pip install -e .
