FROM nvidia/cuda:12.3.1-devel-ubuntu22.04

LABEL author="Shu Zhao, smz5505@psu.edu"
ENV TZ="America/New_York"
ENV MODEL_VERSION="vicuna"
ENV PATH="/root/miniconda3/bin:$PATH"

# Install basic packages
RUN apt update && DEBIAN_FRONTEND=noninteractive apt install -y tzdata \
  && apt install -y git wget \
  && apt-get autoremove -y \
  && apt-get clean -y \
  && rm -rf /var/lib/apt/lists/*

# Install miniconda
RUN wget \
    https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh \
    && mkdir /root/.conda \
    && bash Miniconda3-latest-Linux-x86_64.sh -b \
    && rm -f Miniconda3-latest-Linux-x86_64.sh
RUN conda create -n dev python=3.10 -y
RUN echo "source activate dev" > ~/.bashrc
ENV PATH /root/miniconda3/envs/dev/bin:$PATH

# Install Vicuna
WORKDIR /root
RUN pip install --upgrade pip flask && pip install "fschat[model_worker,webui]"

# Deploy flask
COPY ./flask_src /root/flask_src
WORKDIR /root/flask_src

ENTRYPOINT [ "python", "app.py" ]
